### ISSUE TITLE
Cannot write state data

### ISSUE THREAD

**Issue by vunhatchuong** [LmanTW/themify.nvim#2]
I'm on Windows, encounter  this error:

![image](https://github.com/user-attachments/assets/16c38b09-7f55-46fd-ba7b-1497150a43e1)

I think you should use vim specific API like `vim.fn.mkdir`,... Since it has better compatibility than lua `io.open`,...

For example, this is how Folk makes a directory in lazy.nvim: https://github.com/folke/lazy.nvim/blob/48b52b5cfcf8f88ed0aff8fde573a5cc20b1306d/lua/lazy/state.lua#L25

**Comment by LmanTW** [comment]
Thanks for the issue! It should be fixed by now, please let me know if it works!

**Comment by vunhatchuong** [comment]
This is fixed but I found some bugs? And I also have some feedback, suggestion. I'll make a new issue with all of them.
