### ISSUE TITLE
Feedback, Suggestion, Bugs

### ISSUE THREAD

**Issue by vunhatchuong** [LmanTW/themify.nvim#3]
My config:

```lua
return {
    "lmantw/themify.nvim",
    lazy = false,
    opts = {
        "folke/tokyonight.nvim",
        "sho-87/kanagawa-paper.nvim",
        "Yazeed1s/minimal.nvim",
    }}
```

## Bugs

1. Can't add a built-in nvim theme for example `default` and `habamax` because `Invalid repository name`
2. I use the example config and this error appears:
![image](https://github.com/user-attachments/assets/4cd1f898-be58-4b58-b4f3-3079acd1675a)
3. The plugin isn't good at dealing  with removing/delete a theme from the list.
![image](https://github.com/user-attachments/assets/f883ee27-1d45-4c62-834a-ee9f8b56d480)
    In the example above I install `minimal.nvim`, remove the line in `opts`, close then open again. And my UI becomes glitchy.
4. How to add a theme that has dependencies? For example [zenbones](https://github.com/zenbones-theme/zenbones.nvim?tab=readme-ov-file#installation) which depends on Lush.

## Suggestion

1. Add `q` or `ESC` to quit the `Themify` float.
2. In the Manager tab, allow to select individual themes and install/update them instead of install/update all.

**Comment by LmanTW** [comment]
Appreciate for the feedbacks, I'll like to give some of my thoughs:

Bugs:
1. Sounds like a good idea!
2. The branch of the colorscheme in the example config is not correct, I'll fix that.
3. I think that's a Windows compatibility problem, I'll look into that.
4. I'm not sure if I want to add support for dependencies. I might need to look into how many colorschemes actually have dependencies before I make the decision.

Suggestion:
1. Sounds like a good idea!
2. Sounds like a good idea!

Thanks again for all the bug reports and feedbacks! I'll look into them over the next few days.

**Comment by LmanTW** [comment]
Progrsss:

* [x] Built-in colorscheme support.
* [x] Windows compatibility issue.
* [x] `q` or `ESC` for closing the window. 
* [x] Install, update individual colorscheme.

**Comment by LmanTW** [comment]
I looked over 94 colorschemes, only 6 of them have dependencies. Since this is not a common situation, using another plugin manager for handling dependencies would be better. I might add an option to manage dependencies through another plugin manager.

**Comment by vunhatchuong** [comment]
Thanks for your hard work, yeah the colorschemes with dependencies situation is hard. Since if someone has that type of colorscheme the compatibility with themify is 0%.
