### ISSUE TITLE
Don't assume main as default

### ISSUE THREAD

**Issue by vunhatchuong** [LmanTW/themify.nvim#8]
### Feature Description

Currently by default the plugin will use `main` which can sometimes make the installation fail if it's not main.

Is there a reason we default to `main` and not just clone it normally?

**Comment by LmanTW** [comment]
Good point! I don't know why I made that decision either, it should be fixed now.

**Comment by vunhatchuong** [comment]
Hmm I think that commit breaks something, now even after I download all the colors the next time I open themify after closing nvim I need to down some again

**Comment by LmanTW** [comment]
Yeah I also fixed that 😅, try update Themify again.

**Comment by vunhatchuong** [comment]
Yep, fixed! Thank you for the amazing work
